services:
  - type: web
    name: app-rag-cadastrale
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app_rag_cadastrale_render.py --server.port 10000 --server.address 0.0.0.0
    envVars:
      - key: OPENAI_API_KEY
        sync: false
    region: frankfurt
    branch: main
    repo: https://github.com/bambangom/app_rag_cadastrale_render
buildCommand: pip install -r requirements.txt
startCommand: streamlit run app_rag_cadastrale_render.py --server.port $PORT --server.headless true --server.enableXsrfProtection false --server.enableCORS false



