services:
  - type: web
    name: app-rag-cadastrale-render
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app_rag_cadastrale_render.py --server.port 10000
    envVars:
      - key: OPENAI_API_KEY
        sync: true
