services:
  - type: web
    name: app-rag-cadastrale-render
    env: python
    plan: free
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "streamlit run app_rag_cadastrale_render.py --server.port $PORT --server.address 0.0.0.0"
    envVars:
      - key: OPENAI_API_KEY
        sync: false
    autoDeploy: true
    envSpecific:
      PORT: 10000
