services:
  - type: web
    name: ia-cadastrale-rag
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app_rag_cadastrale_render.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
